"""Add division

Revision ID: f8e4644429c4
Revises: 561624c47f78
Create Date: 2024-11-30 21:31:08.352168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8e4644429c4'
down_revision: Union[str, None] = '561624c47f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_id'), 'division', ['id'], unique=False)
    op.add_column('employee', sa.Column('division_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employee', 'division', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'division_id')
    op.drop_index(op.f('ix_division_id'), table_name='division')
    op.drop_table('division')
    # ### end Alembic commands ###
